# Generated by Django 5.2.12 on 2026-04-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='avaliacao_tipo',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='curso',
            field=models.CharField(default='1', max_length=100, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='pessoa',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name=' Frequência da Pessoa'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina da Ausência/Presença'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='numero_faltas',
            field=models.CharField(default='1', max_length=100, verbose_name='Numero de Faltas'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_inicio',
            field=models.DateField(max_length=100, verbose_name='Data de Início da Matrícula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_previsao_termino',
            field=models.DateField(max_length=100, verbose_name='Data de Previsão do Término do Curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='instituicao_ensino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(max_length=100, verbose_name='Data da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nasc',
            field=models.DateField(max_length=100, verbose_name='Data de Nascimento da pessoa'),
        ),
    ]
